feat(scripts): server launch script improved

diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
+#
+# Check for requirements and then hosts the website with `uvicorn` at port 8000
 
-function log() {
+function log()
+{
     color=$1
     message=$2
 
@@ -11,47 +14,78 @@ function log() {
     esac
 }
 
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-VENV_BIN="$SCRIPT_DIR/.venv/bin"
-
-if [[ ! -f $SCRIPT_DIR/.venv/bin/activate ]];then
-    log 'red' "virtual environment not detected"
-    python3 -m venv $SCRIPT_DIR/.venv
-    log 'green' "virtual environment created at '$SCRIPT_DIR/.venv/'"
-    source $VENV_BIN/activate
-    pip install -r $SCRIPT_DIR/requirements.txt
-    log 'green' "requirements installed"
-    log 'green' "starting application"
+function start_application() 
+{
+    log "green" "starting application"
     exec uvicorn app.main:app --reload --port 8000
+}
+
+function create_virtual_environment()
+{
+    if python3 -m venv $SCRIPT_DIR/.venv; then 
+      echo log "green" "virtual environment created at '$SCRIPT_DIR/.venv/'"
+    else 
+      log "red" "could not create virtual environment" && exit 1 
+    fi
+}
+
+function install_requirements()
+{
+    source $VENV_IS_IN_PATH/activate
+    
+    if pip install -r $SCRIPT_DIR/requirements.txt; then
+      log "green" "requirements installed"
+    else
+      log "red" "couldnot install requirements" && exit 1
+    fi
+}
+
+function requirements_are_installed()
+{
+    while IFS= read -r package; do
+        [[ -z "$package" || "$package" =~ ^# ]] && continue
+
+        if ! pip show "$package" >/dev/null 2>&1; then
+            return 1
+        fi
+    done < "$SCRIPT_DIR/requirements.txt"
+    return 0 
+}
+
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+VENV_ACTIVATE_PATH="$SCRIPT_DIR/.venv/bin/activate"
+VENV_EXISTS=$VENV_ACTIVATE_PATH
+VENV_BIN="$SCRIPT_DIR/.venv/bin"
+VENV_IS_IN_PATH=$VENV_BIN
+
+if [[ ! -f $VENV_EXISTS ]];then
+    log "red" "virtual environment not detecting, creating virtual environment..."
+    create_virtual_environment
+    install_requirements
+    start_application
 else
-    log 'green' "virtual environment detected"
+    log "green" "virtual environment detected"
     case "$PATH:" in
-        "$VENV_BIN:"*)
-            log 'green' "'.venv/bin/activate' is in PATH"
-            if pip install --dry-run -r $SCRIPT_DIR/requirements.txt >/dev/null 2>&1;then
-                log 'green' "requirements installed"
-                log 'green' "starting application"
-                exec uvicorn app.main:app --reload --port 8000
+        "$VENV_IS_IN_PATH:"*)
+            log "green" "'.venv/bin/activate' is in PATH"
+            if requirements_are_installed;then
+                log "green" "requirements installed"
+                start_application
             else
-                pip install -r $SCRIPT_DIR/requirements.txt
-                log 'green' "requirements installed"
-                log 'green' "starting application"
-                exec uvicorn app.main:app --reload --port 8000
-            fi
-            ;;
+                log "red" "requirements not installed, installing..."
+                install_requirements
+                start_application
+            fi ;;
         *)
-            log 'red' "'.venv/bin/activate' is not in PATH, consider running 'source .venv/bin/activate'"
-            source $VENV_BIN/activate
-            if pip install --dry-run -r $SCRIPT_DIR/requirements.txt >/dev/null 2>&1;then
-                log 'green' "requirements installed"
-                log 'green' "starting application"
-                exec uvicorn app.main:app --reload --port 8000
+            log "red" "'.venv/bin/activate' is not in PATH, consider running 'source .venv/bin/activate'"
+            source $VENV_ACTIVATE_PATH
+            if requirements_are_installed;then
+                log "green" "requirements installed"
+                start_application
             else
-                pip install -r $SCRIPT_DIR/requirements.txt
-                log 'green' "requirements installed"
-                log 'green' "starting application"
-                exec uvicorn app.main:app --reload --port 8000
-            fi
-            ;;
+                log "red" "requirements not installed, installing..."
+                install_requirements
+                start_application
+            fi ;;
         esac
 fi
